# data-access
spring:
  profiles: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10103/eureka/
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 120000
  ConnectTimeout: 30000