spring:
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10103/eureka/
---
spring:
  profiles: test
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 120000
  ConnectTimeout: 30000