spring.profiles.active: dev

---
# dev profiles
spring:
  profiles: dev
  application:
    name: sce-zuul-service
  cloud:
    config:
      uri: http://localhost:10099
logging:
  file: ./logs/dev_app.log
  pattern:
    console: "%highlight{[%d{DEFAULT}] %highlight{%-5level}{FATAL=Bright red, ERROR=Bright red, WARN=Bright Yellow, INFO=Bright Green, DEBUG=Bright Cyan} %style{[%-25.25t]}{Yellow} %style{%-40c{1.}}{Cyan} : %m%n%ex}"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: INFO
    guru.springframework.controllers: DEBUG
    org.hibernate: DEBUG
server:
  port: 11000
