spring.profiles.active: dev

---
# dev profiles
spring:
  profiles: dev
  application:
    name: sce-zuul-service
  cloud:
    config:
      uri: http://localhost:10099
logging:
  file: ./logs/dev_app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: INFO
    guru.springframework.controllers: DEBUG
    org.hibernate: DEBUG
server:
  port: 11000
