spring.profiles.active: native
---
spring:
  application:
    name: sce-config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
server:
  port: 10099
  servlet:
    context-path: /
logging:
  file: ./logs/dev_app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: INFO
    guru.springframework.controllers: INFO
    org.hibernate: INFO